### ISSUE TITLE
hey, this is buggy

### ISSUE THREAD

**Issue by lastch** [InvokerMaster/TeamMan-ReactNative#3]
contact me, i need to teach you something

**Comment by lastch** [comment]
@InvokerMaster

**Comment by InvokerMaster** [comment]
where ? email? let me know

**Comment by lastch** [comment]
google hangout, elicloudh@gmail.com

**Comment by InvokerMaster** [comment]
sent

**Comment by lastch** [comment]
received nothing

**Comment by InvokerMaster** [comment]
![image](https://user-images.githubusercontent.com/31196185/77827402-c4d2db80-70eb-11ea-9691-e5a4f35a339f.png)

**Comment by lastch** [comment]
strange, let me know your email

**Comment by InvokerMaster** [comment]
tannai.odin@gmail.com
